/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLiveUsersRouteImport } from './routes/admin/live-users'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNetworkRouteImport } from './routes/admin/network'
import { Route as AdminNetworkMapRouteImport } from './routes/admin/network-map'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminVouchersRouteImport } from './routes/admin/vouchers'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalAccountRouteImport } from './routes/portal/account'
import { Route as PortalAddDeviceRouteImport } from './routes/portal/add-device'
import { Route as PortalAuthRouteImport } from './routes/portal/auth'
import { Route as PortalConnectRouteImport } from './routes/portal/connect'
import { Route as PortalExpiredRouteImport } from './routes/portal/expired'
import { Route as PortalPackagesRouteImport } from './routes/portal/packages'
import { Route as PortalPaymentRouteImport } from './routes/portal/payment'
import { Route as PortalPaymentStatusRouteImport } from './routes/portal/payment-status'
import { Route as PortalRecoverRouteImport } from './routes/portal/recover'
import { Route as PortalRewardsRouteImport } from './routes/portal/rewards'
import { Route as PortalVoucherRouteImport } from './routes/portal/voucher'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronTickRouteImport } from './routes/api/cron.tick'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api/mpesa.callback'
import { Route as ApiPayCallbackRouteImport } from './routes/api/pay.callback'
import { Route as PortalLegalDocRouteImport } from './routes/portal/legal.$doc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLiveUsersRoute = AdminLiveUsersRouteImport.update({
  id: '/live-users',
  path: '/live-users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNetworkMapRoute = AdminNetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAddDeviceRoute = PortalAddDeviceRouteImport.update({
  id: '/add-device',
  path: '/add-device',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAuthRoute = PortalAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalConnectRoute = PortalConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalExpiredRoute = PortalExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPackagesRoute = PortalPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPaymentRoute = PortalPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPaymentStatusRoute = PortalPaymentStatusRouteImport.update({
  id: '/payment-status',
  path: '/payment-status',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalRecoverRoute = PortalRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalRewardsRoute = PortalRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalVoucherRoute = PortalVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa/callback',
  path: '/api/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayCallbackRoute = ApiPayCallbackRouteImport.update({
  id: '/api/pay/callback',
  path: '/api/pay/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLegalDocRoute = PortalLegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => PortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/live-users': typeof AdminLiveUsersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/network-map': typeof AdminNetworkMapRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/add-device': typeof PortalAddDeviceRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/connect': typeof PortalConnectRoute
  '/portal/expired': typeof PortalExpiredRoute
  '/portal/packages': typeof PortalPackagesRoute
  '/portal/payment': typeof PortalPaymentRoute
  '/portal/payment-status': typeof PortalPaymentStatusRoute
  '/portal/recover': typeof PortalRecoverRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/voucher': typeof PortalVoucherRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/pay/callback': typeof ApiPayCallbackRoute
  '/portal/legal/$doc': typeof PortalLegalDocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/live-users': typeof AdminLiveUsersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/network-map': typeof AdminNetworkMapRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/add-device': typeof PortalAddDeviceRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/connect': typeof PortalConnectRoute
  '/portal/expired': typeof PortalExpiredRoute
  '/portal/packages': typeof PortalPackagesRoute
  '/portal/payment': typeof PortalPaymentRoute
  '/portal/payment-status': typeof PortalPaymentStatusRoute
  '/portal/recover': typeof PortalRecoverRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/voucher': typeof PortalVoucherRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/pay/callback': typeof ApiPayCallbackRoute
  '/portal/legal/$doc': typeof PortalLegalDocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/live-users': typeof AdminLiveUsersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/network-map': typeof AdminNetworkMapRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/add-device': typeof PortalAddDeviceRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/connect': typeof PortalConnectRoute
  '/portal/expired': typeof PortalExpiredRoute
  '/portal/packages': typeof PortalPackagesRoute
  '/portal/payment': typeof PortalPaymentRoute
  '/portal/payment-status': typeof PortalPaymentStatusRoute
  '/portal/recover': typeof PortalRecoverRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/voucher': typeof PortalVoucherRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/pay/callback': typeof ApiPayCallbackRoute
  '/portal/legal/$doc': typeof PortalLegalDocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/portal'
    | '/login'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/live-users'
    | '/admin/login'
    | '/admin/network'
    | '/admin/network-map'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vouchers'
    | '/portal/account'
    | '/portal/add-device'
    | '/portal/auth'
    | '/portal/connect'
    | '/portal/expired'
    | '/portal/packages'
    | '/portal/payment'
    | '/portal/payment-status'
    | '/portal/recover'
    | '/portal/rewards'
    | '/portal/voucher'
    | '/admin/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/cron/tick'
    | '/api/mpesa/callback'
    | '/api/pay/callback'
    | '/portal/legal/$doc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/live-users'
    | '/admin/login'
    | '/admin/network'
    | '/admin/network-map'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vouchers'
    | '/portal/account'
    | '/portal/add-device'
    | '/portal/auth'
    | '/portal/connect'
    | '/portal/expired'
    | '/portal/packages'
    | '/portal/payment'
    | '/portal/payment-status'
    | '/portal/recover'
    | '/portal/rewards'
    | '/portal/voucher'
    | '/admin'
    | '/portal'
    | '/api/auth/$'
    | '/api/cron/tick'
    | '/api/mpesa/callback'
    | '/api/pay/callback'
    | '/portal/legal/$doc'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/portal'
    | '/login'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/live-users'
    | '/admin/login'
    | '/admin/network'
    | '/admin/network-map'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vouchers'
    | '/portal/account'
    | '/portal/add-device'
    | '/portal/auth'
    | '/portal/connect'
    | '/portal/expired'
    | '/portal/packages'
    | '/portal/payment'
    | '/portal/payment-status'
    | '/portal/recover'
    | '/portal/rewards'
    | '/portal/voucher'
    | '/admin/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/cron/tick'
    | '/api/mpesa/callback'
    | '/api/pay/callback'
    | '/portal/legal/$doc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiPayCallbackRoute: typeof ApiPayCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/live-users': {
      id: '/admin/live-users'
      path: '/live-users'
      fullPath: '/admin/live-users'
      preLoaderRoute: typeof AdminLiveUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/network-map': {
      id: '/admin/network-map'
      path: '/network-map'
      fullPath: '/admin/network-map'
      preLoaderRoute: typeof AdminNetworkMapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/add-device': {
      id: '/portal/add-device'
      path: '/add-device'
      fullPath: '/portal/add-device'
      preLoaderRoute: typeof PortalAddDeviceRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/auth': {
      id: '/portal/auth'
      path: '/auth'
      fullPath: '/portal/auth'
      preLoaderRoute: typeof PortalAuthRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/connect': {
      id: '/portal/connect'
      path: '/connect'
      fullPath: '/portal/connect'
      preLoaderRoute: typeof PortalConnectRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/expired': {
      id: '/portal/expired'
      path: '/expired'
      fullPath: '/portal/expired'
      preLoaderRoute: typeof PortalExpiredRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/packages': {
      id: '/portal/packages'
      path: '/packages'
      fullPath: '/portal/packages'
      preLoaderRoute: typeof PortalPackagesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/payment': {
      id: '/portal/payment'
      path: '/payment'
      fullPath: '/portal/payment'
      preLoaderRoute: typeof PortalPaymentRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/payment-status': {
      id: '/portal/payment-status'
      path: '/payment-status'
      fullPath: '/portal/payment-status'
      preLoaderRoute: typeof PortalPaymentStatusRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/recover': {
      id: '/portal/recover'
      path: '/recover'
      fullPath: '/portal/recover'
      preLoaderRoute: typeof PortalRecoverRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/rewards': {
      id: '/portal/rewards'
      path: '/rewards'
      fullPath: '/portal/rewards'
      preLoaderRoute: typeof PortalRewardsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/voucher': {
      id: '/portal/voucher'
      path: '/voucher'
      fullPath: '/portal/voucher'
      preLoaderRoute: typeof PortalVoucherRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/callback': {
      id: '/api/mpesa/callback'
      path: '/api/mpesa/callback'
      fullPath: '/api/mpesa/callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/callback': {
      id: '/api/pay/callback'
      path: '/api/pay/callback'
      fullPath: '/api/pay/callback'
      preLoaderRoute: typeof ApiPayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/legal/$doc': {
      id: '/portal/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/portal/legal/$doc'
      preLoaderRoute: typeof PortalLegalDocRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLiveUsersRoute: typeof AdminLiveUsersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminNetworkMapRoute: typeof AdminNetworkMapRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLiveUsersRoute: AdminLiveUsersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminNetworkMapRoute: AdminNetworkMapRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalAddDeviceRoute: typeof PortalAddDeviceRoute
  PortalAuthRoute: typeof PortalAuthRoute
  PortalConnectRoute: typeof PortalConnectRoute
  PortalExpiredRoute: typeof PortalExpiredRoute
  PortalPackagesRoute: typeof PortalPackagesRoute
  PortalPaymentRoute: typeof PortalPaymentRoute
  PortalPaymentStatusRoute: typeof PortalPaymentStatusRoute
  PortalRecoverRoute: typeof PortalRecoverRoute
  PortalRewardsRoute: typeof PortalRewardsRoute
  PortalVoucherRoute: typeof PortalVoucherRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalLegalDocRoute: typeof PortalLegalDocRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalAddDeviceRoute: PortalAddDeviceRoute,
  PortalAuthRoute: PortalAuthRoute,
  PortalConnectRoute: PortalConnectRoute,
  PortalExpiredRoute: PortalExpiredRoute,
  PortalPackagesRoute: PortalPackagesRoute,
  PortalPaymentRoute: PortalPaymentRoute,
  PortalPaymentStatusRoute: PortalPaymentStatusRoute,
  PortalRecoverRoute: PortalRecoverRoute,
  PortalRewardsRoute: PortalRewardsRoute,
  PortalVoucherRoute: PortalVoucherRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalLegalDocRoute: PortalLegalDocRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiPayCallbackRoute: ApiPayCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
